using Exercicio5;
Pessoa pessoa1 = new Pessoa("João", 30);
pessoa1.ExibirDados();
Console.WriteLine($"");
Console.WriteLine($"");
Funcionario funcionario1 = new Funcionario();
funcionario1.Nome = "Maria";
funcionario1.Idade = 25;
funcionario1.Salario = 5000.0;
funcionario1.ExibirDados();